cmake_minimum_required(VERSION 3.13)
if(NOT PICO_SDK_PATH)
    set(PICO_SDK_PATH "$ENV{PICO_SDK_PATH}")
endif()
include(${PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(gb_cart_programmer C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(gb_cart_programmer src/main.c)
pico_set_program_version(gb_cart_programmer "3.0")
target_link_libraries(gb_cart_programmer pico_stdlib hardware_spi)
target_compile_options(gb_cart_programmer PRIVATE -Wall -Wextra -Werror)
pico_enable_stdio_usb(gb_cart_programmer 1)
pico_enable_stdio_uart(gb_cart_programmer 0)
pico_add_extra_outputs(gb_cart_programmer)
